# Generated by Django 5.2.10 on 2026-03-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("category_id", models.CharField(blank=True, max_length=50, null=True)),
                ("size", models.IntegerField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                ("cost_price", models.IntegerField()),
                ("selling_price", models.IntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegisterUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
