# Generated by Django 6.0.3 on 2026-03-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDshop', '0002_registeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
