# Generated by Django 6.0.3 on 2026-03-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDshop', '0003_alter_registeruser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('customer', models.CharField(max_length=100)),
                ('items', models.IntegerField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
