# Generated by Django 6.0.3 on 2026-03-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDshop', '0004_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=50),
        ),
    ]
