# Generated by Django 5.2.10 on 2026-04-14 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="contact_number",
            new_name="contact",
        ),
    ]
