# Generated by Django 5.2.10 on 2026-04-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_rename_contact_number_userprofile_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="contact",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
