# Generated by Django 5.2.10 on 2026-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_remove_userprofile_contact_userprofile_custom_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="contact",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
