# Generated by Django 5.2.10 on 2026-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_userprofile_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_id",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="custom_id",
            field=models.CharField(blank=True, default=5, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
