# Generated by Django 5.2.10 on 2026-04-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_product_category_id_product_price_product_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category_id",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Hand Tools", "Hand Tools"),
                    ("Power Tools", "Power Tools"),
                    ("Measuring Tools", "Measuring Tools"),
                    ("Cutting Tools", "Cutting Tools"),
                    ("Safety Equipment", "Safety Equipment"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(max_length=50),
        ),
    ]
